function createfigure(X1, Y1, Z1, S1, C1)
%CREATEFIGURE(X1, Y1, Z1, S1, C1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c

%  Auto-generated by MATLAB on 22-Mar-2022 08:46:51

% Create figure
figure;
colormap(jet);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerEdgeColor','none','AlphaDataMapping','none',...
    'MarkerFaceColor','flat');

% Create light
light('Parent',axes1,...
    'Position',[-0.00139027126031673 -0.000149741619848914 0.999999022361157]);

% Create zlabel
zlabel('Temperture (C^\circ)','FontWeight','bold');

% Create ylabel
ylabel('Extent of Reduction (\delta)','FontWeight','bold','Rotation',-18);

% Create xlabel
xlabel('Mol Fraction Ba (x)','FontWeight','bold','Rotation',13);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.01 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.01 0.5]);
view(axes1,[-39.8633663373767 18.5211155360643]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','FontSize',14,'FontWeight','bold','LineWidth',2,...
    'XMinorTick','on','YMinorTick','on');
% Create colorbar
colorbar(axes1,'northoutside');

